import MollifyWebApp from '../../images/MollifyWebApp.jpeg'
import ECommerce from '../../images/E-commerce.png'
import MollifyWebPage from '../../images/MollifyWebPage.png'
import marsApp from '../../images/marsapp.png'
import burgerApp from '../../images/burgerApp.png'
import memories from '../../images/memories.png'
import forkify from '../../images/forkify.png'
import mapty from '../../images/mapty.png'
import bankerList from '../../images/bankerList.png'
import whatsapp from '../../images/whatsapp.png'
import tinder from '../../images/tinder.png'
import portfolio from '../../images/portfolio.png'
import pigGame from '../../images/pigGame.png'
import budgety from '../../images/budgety.png'
import notesApp from '../../images/notesApp.png'
import nexter from '../../images/nexter.png'
import naturous from '../../images/naturous.png'
import atlas from '../../images/atlas.png'
import webpage from '../../images/tinder_e_hamdard.png'
import meditationApp from '../../images/meditationApp.png'

export const desktopCardList = [
  {
    gridRow: '1 / 6',
    gridColumn: '1 / 5',
    backgroundColor: 'yellow',
    isSmall: false,
    name: 'Mollify Web-App',
    info: 'A web-app where patients can find psychiatrist and request session both doctor and patient can navigate each other from there present location. It have different UI for patients and doctors. Technology stack used:- React.js, Node.js, Express, Redux, MongoDb, JWT, Material UI, Geolocation api, MapboxGL, Chart.js,  Designed using Figma, deployed on Heroku.',
    viewLink: 'https://focused-brattain-9df5b1.netlify.app/',
    gitLink: 'https://github.com/yahya-cloud/mollify-webapp',
    imgUrl: { MollifyWebApp },
  },
  {
    gridRow: '6 / 11',
    gridColumn: '1 / 5',
    backgroundColor: 'grey',
    isSmall: false,
    name: 'E-commerce app',
    info: 'An E-commerce web app. Users can see all previous order and can pay through paypal. Admin side for adding products on store, managing all orders placed and users on the app. Technology stack:- React.js, Express, Node.js, Mongodb, Redux, JWT, React-Bootstrap, PayPal api ,deployed on Heroku.',
    viewLink: 'https://e-commerce-app-proshop.herokuapp.com/',
    gitLink: 'https://github.com/yahya-cloud/proshop',
    imgUrl: { ECommerce },
  },
  {
    gridRow: '1 / 4',
    gridColumn: '5 / 9',
    backgroundColor: 'pink',
    isSmall: false,
    name: 'Mollify website',
    info: 'A multipage website for introducing the idea of mollify and letting interested people contact us via email. Technology Stack:- Node.js, EJS, Express, SCSS, Chart.js,Email.js, Designed using Figma.',
    viewLink: 'https://frozen-sands-98963.herokuapp.com/',
    gitLink: 'https://github.com/yahya-cloud/mollify-node',
    imgUrl: { MollifyWebPage },
  },

  {
    gridRow: '4 / 7',
    gridColumn: '5 / 7',
    backgroundColor: 'orange',
    isSmall: false,
    name: 'Buger App',
    info: 'Web-app to make desired burger, place order, see order history. Technology Stack:- React.js, Redux, ReduxSaga, Firebase ',
    viewLink: 'https://burger-builder-d34c6.firebaseapp.com',
    gitLink: 'https://github.com/yahya-cloud/burger-app',
    imgUrl: { burgerApp },
  },
  {
    gridRow: '7 / 9',
    gridColumn: ' 5 / 7',
    backgroundColor: 'rgb(255, 46, 46)',
    isSmall: true,
    name: 'BankerList',
    info: 'Technology Stack:- JavaScript, HTML, CSS ',
    viewLink: 'https://yahya-cloud.github.io/bankerlist/',
    gitLink: 'https://github.com/yahya-cloud/bankerlist',
    imgUrl: { bankerList },
  },
  {
    gridRow: '9 / 11',
    gridColumn: '5 / 7',
    backgroundColor: 'lightcoral',
    isSmall: true,
    name: 'whatsapp-clone',
    info: 'Technology Stack:- React.js, Redux, Firebase',
    viewLink: 'https://whatsapp-clone-2aa06.firebaseapp.com/',
    gitLink: 'https://github.com/yahya-cloud/whatsapp-clone',
    imgUrl: { whatsapp },
  },

  {
    gridRow: '4 / 7',
    gridColumn: ' 7 / 9',
    backgroundColor: 'lightsalmon',
    isSmall: false,
    info: 'Js app to get food recipes and amount of ingredients for different number of people. Technology stack:- JS, Webpack, HTML, CSS   ',
    name: 'Forkify',
    viewLink: 'https://agitated-brattain-a2b130.netlify.app/',
    gitLink: 'https://github.com/yahya-cloud/forkify',
    imgUrl: { forkify },
  },
  {
    gridRow: '7 / 9',
    gridColumn: '  7 / 9',
    backgroundColor: 'lawngreen',
    isSmall: true,
    name: 'Mapty',
    info: 'Technology Stack:- JavaScript, Leaflet, HTML, CSS',
    gitLink: 'https://github.com/yahya-cloud/mapty',
    imgUrl: { mapty },
  },
  {
    gridRow: '9 / 11',
    gridColumn: ' 7 / 9',
    backgroundColor: 'lightslategrey',
    isSmall: true,
    name: 'Tinder clone',
    info: 'Technology Stack:- React.js, Redux, Firebase',
    viewLink: 'https://tinder-clone-6ccc5.web.app/',
    gitLink: 'https://github.com/yahya-cloud/tinder-clone',
    imgUrl: { tinder },
  },

  {
    gridRow: '4 / 6',
    gridColumn: ' 9 / 10',
    backgroundColor: 'lightyellow',
    isSmall: true,
    name: 'Portfolio',
    info: 'Tech. Stack:- React.js',
    viewLink: '',
    gitLink: '',
    imgUrl: { portfolio },
  },
  {
    gridRow: '4 / 6',
    gridColumn: '10 / 11',
    backgroundColor: 'lightseagreen',
    isSmall: true,
    name: 'Pig game',
    info: 'Tech. Stack:- Javascript',
    viewLink: 'https://yahya-cloud.github.io/piggame/',
    gitLink: 'https://github.com/yahya-cloud/piggame',
    imgUrl: { pigGame },
  },
  {
    gridRow: '6 / 8',
    gridColumn: '10 / 11',
    backgroundColor: 'rgb(193, 182, 255)',
    isSmall: true,
    name: 'Notes App',
    info: 'Tech. Stack:- React.js',
    viewLink: 'https://w7pvg.csb.app/',
    gitLink: 'https://codesandbox.io/s/keeper-app-w7pvg?file=/src/index.js',
    imgUrl: { notesApp },
  },

  {
    gridRow: '6 / 8',
    gridColumn: ' 9 / 10',
    backgroundColor: 'rgb(236, 154, 61)',
    isSmall: true,
    name: 'Budgety',
    info: 'Tech. Stack:- JavaScript',
    viewLink: 'https://yahya-cloud.github.io/mydatebudget/',
    gitLink: 'https://github.com/yahya-cloud/mydatebudget',
    imgUrl: { budgety },
  },
  {
    gridRow: '8 / 9',
    gridColumn: '9 / 10',
    backgroundColor: 'rgb(104, 61, 12)',
    isSmall: true,
    name: 'Mars App ',
    info: '',
    viewLink: 'https://yahya-cloud.github.io/mars-app/',
    gitLink: 'https://github.com/yahya-cloud/mars-app',
    imgUrl: { marsApp },
  },
  {
    gridRow: '10 / 11',
    gridColumn: '10 / 11',
    backgroundColor: 'rgb(12, 104, 20) ',
    isSmall: true,
    name: 'Js app',
    viewLink: 'https://yahya-cloud.github.io/meditaion-app/',
    gitLink: 'https://github.com/yahya-cloud/mars-app',
    imgUrl: { meditationApp },
  },
  {
    gridRow: '9/10',
    gridColumn: '9/10',
    backgroundColor: 'rgb(26, 159, 177)',
    isSmall: true,
    name: 'Naturous',
    info: 'commonly used to demonstrate the visual',
    viewLink: 'https://yahya-cloud.github.io/natours/',
    gitLink: 'https://github.com/yahya-cloud/natours',
    imgUrl: { naturous },
  },
  {
    gridRow: '9 / 10',
    gridColumn: '10 / 11',
    backgroundColor: 'rgb(177, 129, 26) ',
    isSmall: true,
    name: 'Atlas',
    info: '',
    viewLink: 'https://yahya-cloud.github.io/atalas-creative/',
    gitLink: 'https://github.com/yahya-cloud/atalas-creative',
    imgUrl: { atlas },
  },
  {
    gridRow: '10 / 11',
    gridColumn: '9/10',
    backgroundColor: 'rgb(199, 82, 82)',
    isSmall: true,
    name: 'webpage',
    viewLink: 'https://yahya-cloud.github.io/tider-e-hamdard/',
    gitLink: 'https://yahya-cloud.github.io/tider-e-hamdard/',
    imgUrl: { webpage },
  },
  {
    gridRow: '1 / 4',
    gridColumn: '9/11',
    backgroundColor: 'lavender',
    isSmall: false,
    name: 'Memories',
    info: 'A web-app where people can store there memories see others. Technology Stack:- React.js, Node.js, Redux, Express, MongoDb, JWT, Materiel UI. ',
    viewLink: 'https://sheltered-bayou-78627.herokuapp.com/',
    gitLink: 'https://github.com/yahya-cloud/memories',
    imgUrl: { memories },
  },
  {
    gridRow: '8 / 9 ',
    gridColumn: '10 / 11',
    backgroundColor: 'black',
    isSmall: true,
    name: 'Nexter',
    info: 'commonly used to demonstrate the visual',
    viewLink: 'https://yahya-cloud.github.io/nexter/',
    gitLink: 'https://github.com/yahya-cloud/nexter',
    imgUrl: { nexter },
  },
]

export const mobileCardList = [
  {
    ...desktopCardList[0],
    gridRow: '1 / 5',
    gridColumn: '1 / 5',
    info: 'Technology stack used:- React.js, Node.js, Express, Redux, MongoDb, JWT, Material UI, Geolocation api, MapboxGL, Chart.js.',
    isSmall: true,
  },
  {
    ...desktopCardList[2],
    gridRow: '1 / 3',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
  },
  {
    ...desktopCardList[3],
    gridRow: '3 / 5',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
  },

  {
    ...desktopCardList[1],
    info: 'Technology stack:- React.js, Express, Node.js, Mongodb, Redux, JWT, React-Bootstrap, PayPal api. deployed on Heroku ',
    gridRow: ' 5 / 9',
    gridColumn: '1 / 5',
    isSmall: true,
  },
  {
    ...desktopCardList[6],
    gridRow: '5 / 7',
    gridColumn: '5 / 7 ',
    info: '',
    isSmall: true,
  },
  {  ...desktopCardList[7],
    gridRow: '7 / 9',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
  },
  {
    ...desktopCardList[18],
    info: 'Technology stack:- React.js, Express, Node.js, Mongodb, Redux, JWT, Material UI, PayPal api, deployed on heroku ',
    gridRow: '9 / 13',
    gridColumn: '1 / 5',
    isSmall: true,
  },
  {
    ...desktopCardList[9],
    gridRow: '9 / 11',
    info: '',
    gridColumn: '5 / 7',
    isSmall: true,
    
  },
  {
    ...desktopCardList[4],
    gridRow: '11 / 13',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
    },

  {
    ...desktopCardList[8],
    gridRow: '13 / 15',
    gridColumn: '1 / 3',
    info: '',
    isSmall: true,
    },
  {
    ...desktopCardList[5],
    gridRow: '13 / 15',
    gridColumn: '3 / 5',
    info: '',
    isSmall: true,
   },
  {
    ...desktopCardList[11],
    gridRow: '13 / 15',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
  },

  {
    ...desktopCardList[15],
    gridRow: '15/ 17',
    gridColumn: '1 / 3',
    info: '',
    isSmall: true,
  },
  {
    ...desktopCardList[12],
    gridRow: '15/ 17',
    gridColumn: '3 / 5',
    info: '',
    isSmall: true,
 },
  {
    ...desktopCardList[14],
    gridRow: '15/ 17',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
    },
  {
    ...desktopCardList[13],
    gridRow: '17 / 19',
    gridColumn: '1 / 3',
    info: '',
    isSmall: true,
 },
  {
    ...desktopCardList[16],
    gridRow: '17 / 19',
    gridColumn: '3 / 5',
    info: '',
    isSmall: true,
 },
  {
    ...desktopCardList[17],
    gridRow: '17 / 19',
    gridColumn: '5 / 7',
    info: '',
    isSmall: true,
    },
]
